version: '3.8'

services:
    app_admin:
      image: gotest-image
      container_name: gotest-container
      ports:
        - "8999:8765"
      volumes:
        - cache:/go_cache

volumes:
  cache:
