version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: aadd2255
      POSTGRES_DB: gotest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app_admin:
    image: gotest-image
    container_name: gotest-container
    ports:
      - "8999:8765"
    volumes:
      # - cache:/go_cache
      - ./go/pkg/mod:/go/pkg/mod
    depends_on:
      - postgres



